#!/usr/bin/env php

<?php

set_time_limit(0);

if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
	require_once __DIR__ . '/../vendor/autoload.php';
} else {
	echo 'Please run "composer install" in order to install CodePaxCLI!';
	exit();
}

require_once __DIR__ . '/../src/AppBundle/bootstrap.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new DbvInstallCommand);
$app->add(new DbvInfoCommand());
$app->add(new DbvRunCommand());
$app->add(new DbvNewBaselineCommand());
$app->run();
